PKGDIR   ?= ../..
L4DIR    ?= $(PKGDIR)/../..

TARGET        = libblock_device.a libblock_device.so
SRC_CC        = errand.cc partition.cc virtio_client.cc
REQUIRES_LIBS = libstdc++

include $(L4DIR)/mk/lib.mk
